// This file is auto-generated by the Supabase CLI
// To regenerate: supabase gen types typescript --project-id your_project_id > src/types/supabase.generated.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          timezone: string;
          theme: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          timezone?: string;
          theme?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          timezone?: string;
          theme?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          default_importance: string;
          enable_auto_categorization: boolean;
          enable_auto_associations: boolean;
          enable_duplicate_detection: boolean;
          ai_response_detail: string;
          enable_ai_citations: boolean;
          insight_frequency: string;
          enable_email_notifications: boolean;
          enable_in_app_notifications: boolean;
          enable_weekly_replay: boolean;
          enable_monthly_replay: boolean;
          enable_memory_ai_processing: boolean;
          enable_connection_discovery: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          default_importance?: string;
          enable_auto_categorization?: boolean;
          enable_auto_associations?: boolean;
          enable_duplicate_detection?: boolean;
          ai_response_detail?: string;
          enable_ai_citations?: boolean;
          insight_frequency?: string;
          enable_email_notifications?: boolean;
          enable_in_app_notifications?: boolean;
          enable_weekly_replay?: boolean;
          enable_monthly_replay?: boolean;
          enable_memory_ai_processing?: boolean;
          enable_connection_discovery?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          default_importance?: string;
          enable_auto_categorization?: boolean;
          enable_auto_associations?: boolean;
          enable_duplicate_detection?: boolean;
          ai_response_detail?: string;
          enable_ai_citations?: boolean;
          insight_frequency?: string;
          enable_email_notifications?: boolean;
          enable_in_app_notifications?: boolean;
          enable_weekly_replay?: boolean;
          enable_monthly_replay?: boolean;
          enable_memory_ai_processing?: boolean;
          enable_connection_discovery?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan: string;
          status: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          memory_limit: number;
          storage_limit_mb: number;
          ai_search_monthly_limit: number;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan?: string;
          status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          memory_limit?: number;
          storage_limit_mb?: number;
          ai_search_monthly_limit?: number;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan?: string;
          status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          memory_limit?: number;
          storage_limit_mb?: number;
          ai_search_monthly_limit?: number;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          slug: string;
          description: string | null;
          color: string | null;
          icon: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          slug: string;
          description?: string | null;
          color?: string | null;
          icon?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          color?: string | null;
          icon?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      topics: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          slug: string;
          description: string | null;
          mention_count: number;
          last_mentioned: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          slug: string;
          description?: string | null;
          mention_count?: number;
          last_mentioned?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          mention_count?: number;
          last_mentioned?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      entities: {
        Row: {
          id: string;
          user_id: string;
          entity_type: string;
          name: string;
          slug: string;
          description: string | null;
          mention_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: string;
          name: string;
          slug: string;
          description?: string | null;
          mention_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          mention_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          status: string;
          category_id: string | null;
          start_date: string | null;
          target_date: string | null;
          progress: number;
          is_archived: boolean;
          is_favorite: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          status?: string;
          category_id?: string | null;
          start_date?: string | null;
          target_date?: string | null;
          progress?: number;
          is_archived?: boolean;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          status?: string;
          category_id?: string | null;
          start_date?: string | null;
          target_date?: string | null;
          progress?: number;
          is_archived?: boolean;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          status: string;
          category_id: string | null;
          target_date: string | null;
          progress: number;
          is_archived: boolean;
          is_favorite: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          status?: string;
          category_id?: string | null;
          target_date?: string | null;
          progress?: number;
          is_archived?: boolean;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          status?: string;
          category_id?: string | null;
          target_date?: string | null;
          progress?: number;
          is_archived?: boolean;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      decisions: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          decision: string;
          reasoning: string | null;
          expected_outcome: string | null;
          status: string;
          actual_outcome: string | null;
          decision_date: string | null;
          review_date: string | null;
          is_archived: boolean;
          is_favorite: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          decision: string;
          reasoning?: string | null;
          expected_outcome?: string | null;
          status?: string;
          actual_outcome?: string | null;
          decision_date?: string | null;
          review_date?: string | null;
          is_archived?: boolean;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          decision?: string;
          reasoning?: string | null;
          expected_outcome?: string | null;
          status?: string;
          actual_outcome?: string | null;
          decision_date?: string | null;
          review_date?: string | null;
          is_archived?: boolean;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      memories: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          raw_content: string | null;
          clean_content: string | null;
          summary: string | null;
          memory_type: string;
          category_id: string | null;
          source_type: string;
          source_url: string | null;
          event_date: string;
          importance: string;
          embedding: string | null;
          is_archived: boolean;
          is_favorite: boolean;
          is_private: boolean;
          processing_status: string;
          processing_error: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          raw_content?: string | null;
          clean_content?: string | null;
          summary?: string | null;
          memory_type?: string;
          category_id?: string | null;
          source_type?: string;
          source_url?: string | null;
          event_date?: string;
          importance?: string;
          embedding?: string | null;
          is_archived?: boolean;
          is_favorite?: boolean;
          is_private?: boolean;
          processing_status?: string;
          processing_error?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          raw_content?: string | null;
          clean_content?: string | null;
          summary?: string | null;
          memory_type?: string;
          category_id?: string | null;
          source_type?: string;
          source_url?: string | null;
          event_date?: string;
          importance?: string;
          embedding?: string | null;
          is_archived?: boolean;
          is_favorite?: boolean;
          is_private?: boolean;
          processing_status?: string;
          processing_error?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      memory_topics: {
        Row: {
          id: string;
          memory_id: string;
          topic_id: string;
          confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          memory_id: string;
          topic_id: string;
          confidence?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          memory_id?: string;
          topic_id?: string;
          confidence?: number;
          created_at?: string;
        };
      };
      memory_entities: {
        Row: {
          id: string;
          memory_id: string;
          entity_id: string;
          confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          memory_id: string;
          entity_id: string;
          confidence?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          memory_id?: string;
          entity_id?: string;
          confidence?: number;
          created_at?: string;
        };
      };
      memory_projects: {
        Row: {
          id: string;
          memory_id: string;
          project_id: string;
          confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          memory_id: string;
          project_id: string;
          confidence?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          memory_id?: string;
          project_id?: string;
          confidence?: number;
          created_at?: string;
        };
      };
      memory_goals: {
        Row: {
          id: string;
          memory_id: string;
          goal_id: string;
          confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          memory_id: string;
          goal_id: string;
          confidence?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          memory_id?: string;
          goal_id?: string;
          confidence?: number;
          created_at?: string;
        };
      };
      memory_connections: {
        Row: {
          id: string;
          user_id: string;
          memory_id_1: string;
          memory_id_2: string;
          connection_type: string;
          confidence: number;
          reason: string | null;
          is_approved: boolean | null;
          is_dismissed: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          memory_id_1: string;
          memory_id_2: string;
          connection_type: string;
          confidence?: number;
          reason?: string | null;
          is_approved?: boolean | null;
          is_dismissed?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          memory_id_1?: string;
          memory_id_2?: string;
          connection_type?: string;
          confidence?: number;
          reason?: string | null;
          is_approved?: boolean | null;
          is_dismissed?: boolean;
          created_at?: string;
        };
      };
      files: {
        Row: {
          id: string;
          memory_id: string;
          file_name: string;
          file_path: string;
          file_type: string | null;
          file_size: number | null;
          storage_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          memory_id: string;
          file_name: string;
          file_path: string;
          file_type?: string | null;
          file_size?: number | null;
          storage_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          memory_id?: string;
          file_name?: string;
          file_path?: string;
          file_type?: string | null;
          file_size?: number | null;
          storage_key?: string;
          created_at?: string;
        };
      };
      ai_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          is_saved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          is_saved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          is_saved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: string;
          content: string;
          source_memories: string[];
          citation_data: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: string;
          content: string;
          source_memories?: string[];
          citation_data?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: string;
          content?: string;
          source_memories?: string[];
          citation_data?: Json;
          created_at?: string;
        };
      };
      saved_searches: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          query: string;
          filters: Json;
          is_favorite: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          query: string;
          filters?: Json;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          query?: string;
          filters?: Json;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      daily_replays: {
        Row: {
          id: string;
          user_id: string;
          replay_date: string;
          main_themes: string[] | null;
          key_moments: string | null;
          open_loops: string | null;
          memory_count: number;
          generated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          replay_date: string;
          main_themes?: string[] | null;
          key_moments?: string | null;
          open_loops?: string | null;
          memory_count?: number;
          generated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          replay_date?: string;
          main_themes?: string[] | null;
          key_moments?: string | null;
          open_loops?: string | null;
          memory_count?: number;
          generated_at?: string;
        };
      };
      weekly_replays: {
        Row: {
          id: string;
          user_id: string;
          week_start_date: string;
          main_focus: string | null;
          biggest_progress: string | null;
          important_memories: string[] | null;
          projects_moved_forward: string[] | null;
          goals_updated: string[] | null;
          decisions_made: string[] | null;
          new_connections: number;
          open_loops: string | null;
          memory_count: number;
          generated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          week_start_date: string;
          main_focus?: string | null;
          biggest_progress?: string | null;
          important_memories?: string[] | null;
          projects_moved_forward?: string[] | null;
          goals_updated?: string[] | null;
          decisions_made?: string[] | null;
          new_connections?: number;
          open_loops?: string | null;
          memory_count?: number;
          generated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          week_start_date?: string;
          main_focus?: string | null;
          biggest_progress?: string | null;
          important_memories?: string[] | null;
          projects_moved_forward?: string[] | null;
          goals_updated?: string[] | null;
          decisions_made?: string[] | null;
          new_connections?: number;
          open_loops?: string | null;
          memory_count?: number;
          generated_at?: string;
        };
      };
      monthly_replays: {
        Row: {
          id: string;
          user_id: string;
          month: string;
          summary: string | null;
          statistics: Json;
          memories_captured: number;
          projects_started: number;
          goals_progressed: number;
          decisions_made: number;
          connections_found: number;
          important_topics: string[] | null;
          generated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          month: string;
          summary?: string | null;
          statistics?: Json;
          memories_captured?: number;
          projects_started?: number;
          goals_progressed?: number;
          decisions_made?: number;
          connections_found?: number;
          important_topics?: string[] | null;
          generated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          month?: string;
          summary?: string | null;
          statistics?: Json;
          memories_captured?: number;
          projects_started?: number;
          goals_progressed?: number;
          decisions_made?: number;
          connections_found?: number;
          important_topics?: string[] | null;
          generated_at?: string;
        };
      };
      integrations: {
        Row: {
          id: string;
          user_id: string;
          provider: string;
          name: string;
          is_connected: boolean;
          access_token: string | null;
          refresh_token: string | null;
          token_expires_at: string | null;
          permissions: Json;
          last_sync: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: string;
          name: string;
          is_connected?: boolean;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expires_at?: string | null;
          permissions?: Json;
          last_sync?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: string;
          name?: string;
          is_connected?: boolean;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expires_at?: string | null;
          permissions?: Json;
          last_sync?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      imports: {
        Row: {
          id: string;
          user_id: string;
          source_type: string;
          file_name: string | null;
          status: string;
          total_items: number;
          processed_items: number;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          source_type: string;
          file_name?: string | null;
          status?: string;
          total_items?: number;
          processed_items?: number;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          source_type?: string;
          file_name?: string | null;
          status?: string;
          total_items?: number;
          processed_items?: number;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      processing_jobs: {
        Row: {
          id: string;
          user_id: string;
          job_type: string;
          target_id: string;
          status: string;
          payload: Json;
          result: Json | null;
          error_message: string | null;
          retry_count: number;
          max_retries: number;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          job_type: string;
          target_id: string;
          status?: string;
          payload?: Json;
          result?: Json | null;
          error_message?: string | null;
          retry_count?: number;
          max_retries?: number;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          job_type?: string;
          target_id?: string;
          status?: string;
          payload?: Json;
          result?: Json | null;
          error_message?: string | null;
          retry_count?: number;
          max_retries?: number;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
      };
      activity_log: {
        Row: {
          id: string;
          user_id: string;
          action: string;
          target_type: string | null;
          target_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action?: string;
          target_type?: string | null;
          target_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string | null;
          notification_type: string;
          action_url: string | null;
          data: Json;
          is_read: boolean;
          created_at: string;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message?: string | null;
          notification_type: string;
          action_url?: string | null;
          data?: Json;
          is_read?: boolean;
          created_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string | null;
          notification_type?: string;
          action_url?: string | null;
          data?: Json;
          is_read?: boolean;
          created_at?: string;
          read_at?: string | null;
        };
      };
      usage_tracking: {
        Row: {
          id: string;
          user_id: string;
          metric: string;
          value: number;
          period_start: string | null;
          period_end: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          metric: string;
          value?: number;
          period_start?: string | null;
          period_end?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          metric?: string;
          value?: number;
          period_start?: string | null;
          period_end?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
}
